"""Shared schemas and stable column ordering."""

from __future__ import annotations

from datetime import date, datetime
from typing import Any

FIRM_COLUMNS = [
    "run_id",
    "firm_id",
    "rank",
    "company",
    "event_type",
    "event_year",
    "event_label",
    "source_confidence",
    "wayback_tier",
    "primary_domain",
    "website",
    "event_source_url",
    "notes",
]

SNAPSHOT_COLUMNS = [
    "run_id",
    "firm_id",
    "rank",
    "company",
    "event_type",
    "event_year",
    "event_label",
    "relative_timepoint",
    "target_year",
    "target_date",
    "observation_is_future",
    "snapshot_status",
    "capture_source",
    "requested_url",
    "canonical_original_url",
    "archive_timestamp",
    "selected_capture_date",
    "temporal_distance_days",
    "wayback_replay_url",
    "http_status",
    "mime_type",
    "digest",
    "redirect_chain",
    "selection_reason",
    "fallback_attempts",
    "failure_reason",
    "event_year_precision_note",
    "discovered_at",
]

PAGE_COLUMNS = [
    "run_id",
    "firm_id",
    "rank",
    "company",
    "event_type",
    "event_year",
    "event_label",
    "relative_timepoint",
    "target_year",
    "target_date",
    "observation_is_future",
    "capture_source",
    "archive_timestamp",
    "selected_capture_date",
    "temporal_distance_days",
    "snapshot_status",
    "wayback_replay_url",
    "original_archived_url",
    "requested_url",
    "final_url",
    "redirect_chain",
    "http_status",
    "mime_type",
    "fetch_timestamp",
    "fetch_error",
    "content_hash",
    "scheme",
    "hostname",
    "subdomain",
    "registrable_domain",
    "suffix",
    "normalized_url",
    "path",
    "query",
    "crawl_depth",
    "discovered_from_url",
    "page_priority_reason",
    "document_title",
    "meta_description",
    "meta_keywords",
    "html_lang",
    "canonical_url",
    "og_title",
    "og_description",
    "og_site_name",
    "h1_text",
    "h2_text",
    "headings_json",
    "raw_html_path",
    "extracted_text",
    "extraction_method",
    "text_language",
    "character_count",
    "token_count",
    "word_count",
    "extraction_quality_score",
    "boilerplate_ratio",
    "duplicate_content_flag",
    "soft_404_flag",
    "archive_toolbar_removed_flag",
    "likely_navigation_only",
    "usable_for_analysis",
    "exclusion_reason",
]

VISUAL_COLUMNS = [
    "run_id",
    "firm_id",
    "rank",
    "company",
    "relative_timepoint",
    "target_year",
    "archive_timestamp",
    "wayback_replay_url",
    "original_archived_url",
    "rendered_success",
    "viewport_width",
    "viewport_height",
    "screenshot_path",
    "body_background_color",
    "header_background_color",
    "hero_background_color",
    "h1_text",
    "h1_font_family",
    "h1_font_size_px",
    "h1_font_weight",
    "h1_color",
    "computed_style_source",
    "css_stylesheet_count",
    "missing_asset_count",
    "visual_extraction_confidence",
    "visual_extraction_error",
    "dominant_colors_json",
]

QUALITY_SUMMARY_COLUMNS = [
    "run_id",
    "firm_id",
    "rank",
    "company",
    "relative_timepoint",
    "target_year",
    "snapshot_status",
    "pages_attempted",
    "pages_success",
    "pages_usable",
    "pages_excluded",
    "avg_text_chars",
    "flags",
]


def empty_row(columns: list[str]) -> dict[str, Any]:
    return {c: None for c in columns}


def serialize_value(value: Any) -> Any:
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, bool):
        return value
    return value
