"""Shared schemas and stable column ordering."""

from __future__ import annotations

from datetime import date, datetime
from typing import Any

FIRM_COLUMNS = [
    "run_id",
    "firm_id",
    "rank",
    "company",
    "event_type",
    "event_year",
    "event_label",
    "event_date_inferred",
    "event_date_verified",
    "event_date_final",
    "event_date_precision",
    "event_date_source",
    "event_date_verification_status",
    "source_confidence",
    "wayback_tier",
    "primary_domain",
    "website",
    "event_source_url",
    "notes",
]

TIMEPOINT_ORDER = [
    "pre_pre_event",
    "pre_event",
    "event",
    "post_event",
    "post_post_event",
]

SNAPSHOT_COLUMNS = [
    "run_id",
    "firm_id",
    "rank",
    "company",
    "event_type",
    "event_year",
    "event_label",
    "event_date_inferred",
    "event_date_verified",
    "event_date_final",
    "event_date_precision",
    "event_date_source",
    "event_date_verification_status",
    "relative_timepoint",
    "target_year",
    "target_date",
    "target_date_precision",
    "observation_is_future",
    "snapshot_status",
    "capture_source",
    "requested_url",
    "cdx_original_url",
    "canonical_original_url",
    "archive_timestamp",
    "selected_capture_date",
    "temporal_distance_days",
    "temporal_fit_quality",
    "temporal_fit_usable_default",
    "event_snapshot_position",
    "days_from_actual_event",
    "days_between_selected_snapshots",
    "adjacent_period_overlap_flag",
    "homepage_available",
    "relevant_subpages_available",
    "subpage_only_observation",
    "observation_scope",
    "observation_recommendation",
    "analysis_eligible",
    "duplicate_capture_flag",
    "duplicate_capture_winner_timepoint",
    "wayback_replay_url",
    "http_status",
    "mime_type",
    "digest",
    "redirect_chain",
    "selection_reason",
    "fallback_attempts",
    "failure_reason",
    "event_year_precision_note",
    "discovered_at",
]

PAGE_COLUMNS = [
    "run_id",
    "firm_id",
    "rank",
    "company",
    "event_type",
    "event_year",
    "event_label",
    "relative_timepoint",
    "target_year",
    "target_date",
    "observation_is_future",
    "snapshot_status",
    "snapshot_observation_key",
    "analysis_eligible",
    "capture_source",
    "archive_timestamp",
    "page_archive_timestamp",
    "selected_capture_date",
    "temporal_distance_days",
    "temporal_fit_quality",
    "wayback_replay_url",
    "original_archived_url",
    "requested_url",
    "final_url",
    "redirect_chain",
    "http_status",
    "mime_type",
    "fetch_timestamp",
    "fetch_error",
    "content_hash",
    "scheme",
    "hostname",
    "subdomain",
    "registrable_domain",
    "suffix",
    "normalized_url",
    "path",
    "query",
    "crawl_depth",
    "discovered_from_url",
    "page_priority_reason",
    "page_category",
    "page_category_reason",
    "branding_corpus_eligible",
    "branding_corpus_exclusion_reason",
    "governance_metadata_eligible",
    "document_title",
    "meta_description",
    "meta_keywords",
    "html_lang",
    "canonical_url",
    "og_title",
    "og_description",
    "og_site_name",
    "h1_text",
    "h2_text",
    "headings_json",
    "raw_html_path",
    "main_text",
    "visible_text",
    "extracted_text",
    "extraction_method",
    "text_language",
    "text_language_confidence",
    "text_language_method",
    "text_language_reason",
    "character_count",
    "token_count",
    "token_count_reason",
    "word_count",
    "extraction_quality_score",
    "boilerplate_ratio",
    "duplicate_content_flag",
    "soft_404_flag",
    "archive_toolbar_removed_flag",
    "likely_navigation_only",
    "usable_for_analysis",
    "exclusion_reason",
]

GOVERNANCE_METADATA_PAGE_COLUMNS = [
    "run_id",
    "firm_id",
    "company",
    "relative_timepoint",
    "target_date",
    "selected_capture_date",
    "original_archived_url",
    "wayback_replay_url",
    "document_title",
    "extracted_text",
    "managing_directors_raw",
    "legal_representatives_raw",
    "legal_entity_raw",
    "parent_company_raw",
    "registered_address_raw",
    "registration_number_raw",
    "vat_id_raw",
    "extraction_confidence",
    "extraction_notes",
]

GOVERNANCE_METADATA_OBSERVATION_COLUMNS = [
    "run_id",
    "firm_id",
    "company",
    "relative_timepoint",
    "target_date",
    "selected_capture_date",
    "impressum_available",
    "governance_metadata_text",
    "detected_legal_representatives",
    "detected_legal_entity",
    "detected_parent_company",
    "governance_metadata_quality",
    "governance_metadata_source_urls",
]

OBSERVATION_TEXT_SUMMARY_COLUMNS = [
    "run_id",
    "firm_id",
    "company",
    "relative_timepoint",
    "target_date",
    "selected_capture_date",
    "snapshot_status",
    "observation_recommendation",
    "analysis_eligible",
    "n_pages_total",
    "n_pages_fetch_success",
    "n_pages_extraction_usable",
    "n_branding_pages_eligible",
    "n_branding_pages_excluded",
    "n_impressum_pages",
    "n_legal_technical_pages",
    "n_duplicate_pages",
    "total_word_count_all_usable_pages",
    "total_token_count_all_usable_pages",
    "branding_word_count",
    "branding_token_count",
    "governance_metadata_word_count",
    "detected_primary_language",
    "language_distribution_json",
    "n_pages_language_unknown",
    "text_analysis_eligible",
    "text_analysis_exclusion_reason",
    "text_analysis_quality_band",
]

BRANDING_CORPUS_PAGE_COLUMNS = PAGE_COLUMNS + [
    "text_analysis_eligible",
    "text_analysis_quality_band",
]

BRANDING_CORPUS_OBSERVATION_COLUMNS = [
    "run_id",
    "firm_id",
    "company",
    "relative_timepoint",
    "branding_text",
    "branding_word_count",
    "branding_token_count",
    "source_page_count",
    "source_page_urls_json",
    "source_page_categories_json",
    "text_analysis_eligible",
    "text_analysis_quality_band",
]

MANUAL_CORPUS_VALIDATION_COLUMNS = [
    "run_id",
    "firm_id",
    "company",
    "relative_timepoint",
    "target_date",
    "selected_capture_date",
    "page_url",
    "wayback_replay_url",
    "page_category",
    "page_category_correct",
    "branding_corpus_eligibility_correct",
    "legal_technical_exclusion_correct",
    "impressum_layer_correct",
    "token_count_plausible",
    "language_detection_plausible",
    "observation_text_eligibility_correct",
    "reviewer_notes",
    "evidence_url",
]

ANALYSIS_OBSERVATION_COLUMNS = [
    "run_id",
    "firm_id",
    "rank",
    "company",
    "event_type",
    "event_year",
    "event_label",
    "event_date_inferred",
    "event_date_verified",
    "event_date_final",
    "event_date_verification_status",
    "relative_timepoint",
    "target_year",
    "target_date",
    "selected_capture_date",
    "archive_timestamp",
    "temporal_distance_days",
    "temporal_fit_quality",
    "temporal_fit_usable_default",
    "event_snapshot_position",
    "observation_scope",
    "observation_recommendation",
    "analysis_eligible",
    "duplicate_capture_flag",
    "canonical_original_url",
    "wayback_replay_url",
    "snapshot_status",
]

FIRM_COVERAGE_COLUMNS = [
    "firm_id",
    "rank",
    "company",
    "pre_pre_event",
    "pre_event",
    "event",
    "post_event",
    "post_post_event",
]

MANUAL_VALIDATION_COLUMNS = [
    "run_id",
    "firm_id",
    "company",
    "relative_timepoint",
    "target_date",
    "selected_capture_date",
    "temporal_fit_quality",
    "observation_scope",
    "observation_recommendation",
    "original_archived_url",
    "wayback_replay_url",
    "duplicate_capture_flag",
    "correct_company",
    "valid_archived_page",
    "temporally_appropriate",
    "content_extraction_usable",
    "duplicate_capture",
    "reviewer_notes",
    "validation_screenshot_path",
]

VISUAL_COLUMNS = [
    "run_id",
    "firm_id",
    "rank",
    "company",
    "relative_timepoint",
    "target_year",
    "archive_timestamp",
    "wayback_replay_url",
    "original_archived_url",
    "rendered_success",
    "viewport_width",
    "viewport_height",
    "screenshot_path",
    "body_background_color",
    "header_background_color",
    "hero_background_color",
    "h1_text",
    "h1_font_family",
    "h1_font_size_px",
    "h1_font_weight",
    "h1_color",
    "computed_style_source",
    "css_stylesheet_count",
    "missing_asset_count",
    "visual_extraction_confidence",
    "visual_extraction_error",
    "dominant_colors_json",
]

QUALITY_SUMMARY_COLUMNS = [
    "run_id",
    "firm_id",
    "rank",
    "company",
    "relative_timepoint",
    "target_year",
    "snapshot_status",
    "pages_attempted",
    "pages_fetch_success",
    "pages_fetch_failed",
    "pages_extraction_usable",
    "pages_branding_eligible",
    "pages_governance_metadata",
    "pages_excluded_legal_technical",
    "pages_duplicate",
    "pages_excluded",
    "avg_text_chars",
    "flags",
]


def empty_row(columns: list[str]) -> dict[str, Any]:
    return {c: None for c in columns}


def serialize_value(value: Any) -> Any:
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, bool):
        return value
    return value
